version: '3.8'

services:
  tmdbcollector:
    image: ghcr.io/d3v1l1989/tmdbcollector:latest
    container_name: tmdbcollector
    volumes:
      - ./config:/app/config:ro
    env_file:
      - .env
    # Choose which server(s) to sync by editing the command below:
    #   --sync_emby for Emby, --sync_jellyfin for Jellyfin, or both
    command: ["--sync_emby", "--sync_jellyfin"]
    restart: unless-stopped
