version: '3.8'

services:
  emby-collection-manager:
    image: ghcr.io/d3v1l1989/emby-collection-manager:latest
    container_name: emby-collection-manager
    volumes:
      - ./config:/app/config:ro
      - ./traktlists:/app/traktlists:ro
      - ./mdblists:/app/mdblists:ro
    # Configuration is controlled via config.yaml
    # You can still override specific settings with environment variables if needed
    environment:
      - SYNC_TARGET=auto  # Options: auto, emby
    restart: unless-stopped
