# Config file for TMDbCollector
# API keys and server details organized by service

# TMDb configuration
tmdb:
  api_key: "YOUR TMDB API KEY"

# Emby configuration
emby:
  api_key: "YOUR EMBY API KEY"
  server_url: "YOUR EMBY URL"
  user_id: "YOUR EMBY USER ID"


# Custom poster generation settings
poster_settings:
  # Enable/disable custom poster generation when TMDb doesn't provide one
  enable_custom_posters: true
  
  # Template settings
  template_name: "default.png"  # Template file in resources/templates/
  
  # Text settings
  text_color: [255, 255, 255]  # RGB values for text color (white)
  bg_color: [0, 0, 0, 128]     # RGBA values for text background (semi-transparent black)
  text_position: 0.5           # Vertical position of text (0-1), 0.5 = centered
